"""add uploaded_files table and fix task timestamps

Revision ID: 31937a4b9327
Revises: 
Create Date: 2025-06-23 16:44:14.826819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31937a4b9327'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('last_referenced', sa.DateTime(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_filename', 'uploaded_files', ['filename'], unique=False)
    op.create_index('idx_files_session', 'uploaded_files', ['session_id', 'upload_time'], unique=False)
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_index('idx_files_session', table_name='uploaded_files')
    op.drop_index('idx_files_filename', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
