"""add_learning_settings_table_issue_300

Revision ID: 3242bdd246f1
Revises: 6ae2d637325d
Create Date: 2025-11-13 13:54:35.938050

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3242bdd246f1"
down_revision: Union[str, Sequence[str], None] = "6ae2d637325d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "learning_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Master switch for learning system",
        ),
        sa.Column(
            "suggestion_threshold",
            sa.Float(),
            nullable=False,
            comment="Minimum confidence to show suggestions",
        ),
        sa.Column(
            "automation_threshold",
            sa.Float(),
            nullable=False,
            comment="Minimum confidence for automatic execution",
        ),
        sa.Column(
            "auto_apply_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Allow automatic pattern application",
        ),
        sa.Column(
            "notification_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Show learning notifications",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_settings_user_id"), "learning_settings", ["user_id"], unique=True
    )
    op.create_table(
        "list_memberships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("list_id", sa.String(), nullable=False),
        sa.Column("todo_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("added_by", sa.String(), nullable=False),
        sa.Column(
            "list_priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "URGENT", name="todopriority"),
            nullable=True,
        ),
        sa.Column("list_due_date", sa.DateTime(), nullable=True),
        sa.Column("list_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["todo_lists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["todo_id"],
            ["todo_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_membership_added_at", "list_memberships", ["added_at"], unique=False)
    op.create_index("idx_membership_added_by", "list_memberships", ["added_by"], unique=False)
    op.create_index("idx_membership_list", "list_memberships", ["list_id"], unique=False)
    op.create_index(
        "idx_membership_list_due", "list_memberships", ["list_id", "list_due_date"], unique=False
    )
    op.create_index(
        "idx_membership_list_position", "list_memberships", ["list_id", "position"], unique=False
    )
    op.create_index(
        "idx_membership_list_priority",
        "list_memberships",
        ["list_id", "list_priority"],
        unique=False,
    )
    op.create_index("idx_membership_todo", "list_memberships", ["todo_id"], unique=False)
    op.create_index("idx_unique_list_todo", "list_memberships", ["list_id", "todo_id"], unique=True)
    op.drop_constraint(op.f("feedback_user_id_fkey"), "feedback", type_="foreignkey")
    op.create_foreign_key(None, "feedback", "users", ["user_id"], ["id"])
    op.alter_column(
        "learned_patterns",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "learned_patterns",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("personality_profiles", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(
        op.f("personality_profiles_user_id_fkey"), "personality_profiles", type_="foreignkey"
    )
    op.create_foreign_key(None, "personality_profiles", "users", ["user_id"], ["id"])
    op.drop_constraint(op.f("fk_todo_items_items"), "todo_items", type_="foreignkey")
    op.create_foreign_key(None, "todo_items", "items", ["id"], ["id"])
    op.alter_column("user_api_keys", "user_id", existing_type=sa.UUID(), nullable=False)
    op.create_foreign_key(None, "user_api_keys", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_api_keys", type_="foreignkey")
    op.alter_column("user_api_keys", "user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(None, "todo_items", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_todo_items_items"), "todo_items", "items", ["id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "personality_profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("personality_profiles_user_id_fkey"),
        "personality_profiles",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("personality_profiles", "user_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "learned_patterns",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "learned_patterns",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "feedback", type_="foreignkey")
    op.create_foreign_key(
        op.f("feedback_user_id_fkey"), "feedback", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_index("idx_unique_list_todo", table_name="list_memberships")
    op.drop_index("idx_membership_todo", table_name="list_memberships")
    op.drop_index("idx_membership_list_priority", table_name="list_memberships")
    op.drop_index("idx_membership_list_position", table_name="list_memberships")
    op.drop_index("idx_membership_list_due", table_name="list_memberships")
    op.drop_index("idx_membership_list", table_name="list_memberships")
    op.drop_index("idx_membership_added_by", table_name="list_memberships")
    op.drop_index("idx_membership_added_at", table_name="list_memberships")
    op.drop_table("list_memberships")
    op.drop_index(op.f("ix_learning_settings_user_id"), table_name="learning_settings")
    op.drop_table("learning_settings")
    # ### end Alembic commands ###
