"""add action humanizations cache table

Revision ID: 8ef0aa7cbc90
Revises:
Create Date: [autogenerated]
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ef0aa7cbc90"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "action_humanizations",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("action", sa.String(), nullable=False, unique=True, index=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("human_readable", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("usage_count", sa.Integer(), default=0),
        sa.Column("last_used", sa.DateTime(), nullable=True),
    )


def downgrade():
    op.drop_table("action_humanizations")
