#!/usr/bin/env python3
"""
Documentation Metrics Updater

Automatically updates docs/metrics.md with current codebase metrics.
Run this script when documentation needs refreshing.

Usage:
    python scripts/update_docs_metrics.py
"""

import subprocess
from datetime import datetime
from pathlib import Path


def count_tests() -> dict:
    """Count all test files and test functions."""
    try:
        # Quick count of test files
        test_files = list(Path("tests").rglob("test_*.py"))
        contract_tests = (
            list(Path("tests/intent/contracts").glob("test_*.py"))
            if Path("tests/intent/contracts").exists()
            else []
        )
        regression_tests = (
            list(Path("tests/regression").glob("test_*.py"))
            if Path("tests/regression").exists()
            else []
        )

        return {
            "test_files": len(test_files),
            "contract_tests": len(contract_tests),
            "regression_tests": len(regression_tests),
        }
    except Exception as e:
        return {"error": str(e)}


def count_lines() -> dict:
    """Count lines in key directories."""

    def count_in_dir(path: str) -> int:
        try:
            result = subprocess.run(
                f"find {path} -name '*.py' -exec wc -l {{}} + 2>/dev/null | tail -1",
                shell=True,
                capture_output=True,
                text=True,
            )
            return int(result.stdout.split()[0]) if result.stdout else 0
        except Exception:
            return 0

    return {
        "services": count_in_dir("services"),
        "tests": count_in_dir("tests"),
        "web": count_in_dir("web"),
        "cli": count_in_dir("cli"),
    }


def count_adrs() -> int:
    """Count ADRs."""
    try:
        adr_dir = Path("docs/internal/architecture/current/adrs")
        return len(list(adr_dir.glob("adr-*.md"))) if adr_dir.exists() else 0
    except Exception:
        return 0


def count_plugins() -> list:
    """Count plugin implementations."""
    plugins = ["github", "slack", "notion", "calendar"]
    base = Path("services/integrations")
    return [p for p in plugins if (base / p).exists()] if base.exists() else []


def update_metrics_file(metrics: dict):
    """Write metrics to docs/metrics.md"""

    content = f"""# Piper Morgan Codebase Metrics

**Last Updated**: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
**Auto-Generated**: This file is automatically updated by `scripts/update_docs_metrics.py`

---

## Test Coverage

- **Test Files**: {metrics['tests']['test_files']}
- **Contract Tests**: {metrics['tests']['contract_tests']}
- **Regression Tests**: {metrics['tests']['regression_tests']}

---

## Codebase Size

- **Services**: {metrics['lines']['services']:,} lines
- **Tests**: {metrics['lines']['tests']:,} lines
- **Web**: {metrics['lines']['web']:,} lines
- **CLI**: {metrics['lines']['cli']:,} lines

---

## Architecture

- **ADRs**: {metrics['adrs']} architecture decision records

---

## Plugins

- **Operational**: {', '.join(metrics['plugins']) if metrics['plugins'] else 'None'}

---

## How to Update

```bash
python scripts/update_docs_metrics.py
```

*Do not manually edit this file - changes will be overwritten.*

---

*Generated by Documentation Sync Process (PROOF-9)*
"""

    Path("docs").mkdir(exist_ok=True)
    Path("docs/metrics.md").write_text(content)
    print(f"✅ Updated docs/metrics.md")


def main():
    """Main execution."""
    # Verify we're in project root (safeguard against running from wrong directory)
    if not Path("services").exists() or not Path("tests").exists():
        print("❌ ERROR: Must run from project root directory")
        print(f"   Current directory: {Path.cwd()}")
        print("   Expected: Directory containing services/, tests/, docs/")
        print("\n   Usage:")
        print("     cd /path/to/piper-morgan")
        print("     python scripts/update_docs_metrics.py")
        return 1

    print("📊 Gathering metrics...")

    metrics = {
        "tests": count_tests(),
        "lines": count_lines(),
        "adrs": count_adrs(),
        "plugins": count_plugins(),
    }

    print(f"   Test Files: {metrics['tests'].get('test_files', 0)}")
    print(f"   Services: {metrics['lines']['services']:,} lines")
    print(f"   ADRs: {metrics['adrs']}")

    print("\n📝 Updating docs/metrics.md...")
    update_metrics_file(metrics)

    print("\n✅ Documentation metrics updated!")
    print("   Commit this file with your next documentation update.")


if __name__ == "__main__":
    main()
